# Group And Sort Entities

It is a common hunting task to group or sort entities in a variable to gain insight into the entities and orgainze the follow-up hunt steps.

## What you will learn

0. How to group or sort entities?
1. How to `GROUP` entities by an attribute?
2. How to `GROUP` entities by multiple attributes?
3. How to use aggregation functions in `GROUP`?
4. How to `SORT` entities before display?
5. Exercise: group processes by binary/image and count PIDs

### 0. How to gain aggregated information of entities?

Use the [GROUP](https://kestrel.readthedocs.io/en/latest/language.html#group) command to group entities in a variable. The command will create new attributes on the entities to summarize the groups, e.g., `unique_attrY` when groupped by attribute `attrX`.

Use the [SORT](https://kestrel.readthedocs.io/en/latest/language.html#sort) command to sort entities in a variable. Most of the time the order of entities in a variable does not matter, except you try to display them.

### 1. How to `GROUP` entities by an attribute?

In [1]:
# get all network-traffic
conns = GET network-traffic
        FROM file:///tmp/lab101.json
        WHERE [network-traffic:dst_port > 0]
        
src_grps = GROUP conns BY src_ref.value

DISP src_grps

### 2. How to `GROUP` entities by multiple attributes?

In [2]:
src_dst_grps = GROUP conns BY src_ref.value, dst_ref.value

DISP src_dst_grps

### 3. How to use aggregation functions in `GROUP`?

There are 6 aggregation functions you can use in the command [GROUP](https://kestrel.readthedocs.io/en/latest/language.html#group).

In [3]:
# count the number of destination IPs given a source IP
rc_grps = GROUP conns BY network-traffic:src_ref.value WITH COUNT(dst_ref.value)

DISP rc_grps

In [4]:
# rename the count attribute as you like
rc_grps_renamed = GROUP conns BY network-traffic:src_ref.value WITH COUNT(dst_ref.value) AS dst_count

DISP rc_grps_renamed

### 4. How to `SORT` entities before display?

It is a common hunting practice to sort entities based on an attribute such as count or timestamp.

In [5]:
rc_grps_renamed_sorted = SORT rc_grps_renamed BY dst_count

DISP rc_grps_renamed_sorted

In [6]:
# you can combine the two steps into one
DISP rc_grps_renamed SORT BY dst_count

src_ref.value,dst_count
224.0.0.252,169
224.0.0.251,27
10.171.5.141,23
10.184.147.141,18
10.16.100.223,1

### 5. Exercise: group processes by binary/image and count PIDs

Copy the huntflow of **1. How to `FIND` child processes of processes?** from tutorial huntbook **3. Find Connected Entities.ipynb** into the cell below and reexecute the huntflow. Then write a new follow-up hunt step in the next cell to group `scheduled_tasks` by its binary image and count how many processes are executed per each binary on disk.

Tip: the binary image attribute of a process is `binary_ref.name`.\
Tip: use the PID (process attribute: `pid`) as an unique identifier for a process instance executed from the binary.